name: Create a comment on new issues

on:
  issues:
    types: [opened]

permissions: write-all

jobs:
  commnet-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
  
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: create comment with API
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh api -X POST \ 
              https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
              -f body='
              Comment but from the API call not action
              '
